[package]
authors = ["Parity Technologies <admin@parity.io>"]
name = "cumulus-relay-chain-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
polkadot-overseer = { git = "https://github.com/purestake/polkadot", branch = "moonbeam-polkadot-v0.9.31" }
polkadot-service = { git = "https://github.com/purestake/polkadot", branch = "moonbeam-polkadot-v0.9.31" }

cumulus-primitives-core = { path = "../../primitives/core" }

sp-api = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.31" }
sp-blockchain = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.31" }
sp-state-machine = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.31" }
sc-client-api = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.31" }

futures = "0.3.24"
async-trait = "0.1.57"
thiserror = "1.0.37"
jsonrpsee-core = "0.15.1"
parity-scale-codec = "3.2.1"
