[package]
authors = ["Parity Technologies <admin@parity.io>"]
name = "cumulus-relay-chain-rpc-interface"
version = "0.1.0"
edition = "2021"


[dependencies]
polkadot-service = { git = "https://github.com/purestake/polkadot", branch = "moonbeam-polkadot-v0.9.31" }

cumulus-primitives-core = { path = "../../primitives/core" }
cumulus-relay-chain-interface = { path = "../relay-chain-interface" }

sp-api = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.31" }
sp-core = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.31" }
sp-runtime = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.31" }
sp-consensus-babe = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.31" }
sp-authority-discovery = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.31" }
sp-state-machine = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.31" }
sc-client-api = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.31" }
sp-storage = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.31" }
sc-rpc-api = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.31" }
tokio = { version = "1.21.2", features = ["sync"] }

futures = "0.3.24"
futures-timer = "3.0.2"
parity-scale-codec = "3.2.1"
jsonrpsee = { version = "0.15.1", features = ["ws-client"] }
tracing = "0.1.37"
async-trait = "0.1.57"
url = "2.3.1"
backoff = { version = "0.4.0", features = ["tokio"] }
